# Generated by Django 3.1.7 on 2021-05-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=6, null=True)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=30)),
                ('student_id', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('religion', models.CharField(choices=[('พุทธ', 'พุทธ'), ('คริสต์', 'คริสต์'), ('อิสลาม', 'อิสลาม'), ('อื่นๆ', 'อื่นๆ')], max_length=6, null=True)),
                ('allergic_foods', models.CharField(max_length=200, null=True)),
                ('allergic_meds', models.CharField(max_length=200, null=True)),
                ('congenital_disease', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('self_telephone_num', models.CharField(max_length=10)),
                ('parent_telephone_num', models.CharField(max_length=10, null=True)),
                ('line_id', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('passion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
            ],
        ),
    ]
