# Generated by Django 3.1.7 on 2021-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_auth',
            old_name='question_text',
            new_name='email',
        ),
    ]
