# Generated by Django 3.1.7 on 2021-05-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0002_auto_20210503_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='campdata',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
