# Generated by Django 3.1.7 on 2021-05-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0003_campdata_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campdata',
            name='reg_useremail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
