# Generated by Django 3.1.7 on 2021-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0004_campdata_reg_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campdata',
            name='house',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
