# Generated by Django 3.1.7 on 2021-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0005_campdata_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_auth',
            name='division',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
