# Generated by Django 3.1.7 on 2021-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0006_auto_20210527_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='campdata',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
