# Generated by Django 3.1.7 on 2021-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Campdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=30)),
                ('student_id', models.IntegerField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('religion', models.CharField(choices=[('พุทธ', 'พุทธ'), ('คริสต์', 'คริสต์'), ('อิสลาม', 'อิสลาม'), ('อื่นๆ', 'อื่นๆ')], max_length=6)),
                ('allergic_foods', models.CharField(max_length=200)),
                ('allergic_meds', models.CharField(max_length=200)),
                ('congenital_disease', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('self_telephone_num', models.IntegerField(max_length=10)),
                ('parent_telephone_num', models.IntegerField(max_length=10)),
                ('line_id', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('passion', models.TextField()),
            ],
        ),
    ]
