# Generated by Django 3.1.7 on 2021-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_zone', '0002_test_campdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_campdata',
            name='parent_telephone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='self_telephone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
