# Generated by Django 3.1.7 on 2021-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_zone', '0003_auto_20210429_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_campdata',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='allergic_foods',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='allergic_meds',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='congenital_disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='gender',
            field=models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='line_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='parent_telephone_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='passion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='religion',
            field=models.CharField(choices=[('พุทธ', 'พุทธ'), ('คริสต์', 'คริสต์'), ('อิสลาม', 'อิสลาม'), ('อื่นๆ', 'อื่นๆ')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='test_campdata',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
