# Generated by Django 3.1.7 on 2021-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_zone', '0004_auto_20210429_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('division', models.CharField(max_length=100)),
            ],
        ),
    ]
